/**
 * @author Flavio
 */
package tela;

import apoio.BCrypt;
import dao.UsuariosDAO;
import entidade.Usuarios;
import javax.swing.JOptionPane;

public class IfrUsuarios extends javax.swing.JInternalFrame {

    int varID = 0;

    public IfrUsuarios() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        tfdEmail = new javax.swing.JTextField();
        tfpSenha = new javax.swing.JPasswordField();
        tfpConfirmaSenha = new javax.swing.JPasswordField();
        cbxSituacao = new javax.swing.JCheckBox();
        pnlConsulta = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfdConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        scrollConsultar = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        btnDesbloquear = new javax.swing.JButton();
        btnBloquear = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setTitle("Cadastro de Usuários");

        jLabel1.setText("Nome:");

        jLabel2.setText("E-mail:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirma Senha:");

        cbxSituacao.setText("Usuário Ativo");

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdNome, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                            .addComponent(tfdEmail)))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSituacao)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(tfpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfpConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfpConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbxSituacao)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", pnlCadastro);

        jLabel3.setText("Busca");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "E-mail", "Situação"
            }
        ));
        scrollConsultar.setViewportView(tblConsulta);

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(pnlConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar)))
                .addContainerGap())
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", pnlConsulta);

        btnDesbloquear.setText("Desbloquear");
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });

        btnBloquear.setText("Bloquear");
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnDesbloquear)
                .addGap(18, 18, 18)
                .addComponent(btnBloquear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBloquear, btnDesbloquear, btnEditar, btnFechar, btnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnBloquear)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnDesbloquear))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
        int row = tblConsulta.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Usuário na Tabela Consulta!");
        } else {
            String idTabela = String.valueOf(tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0));
            varID = Integer.parseInt(idTabela);
            if (new UsuariosDAO().bloquear(varID) == null) {
                JOptionPane.showMessageDialog(this, "Usuário Bloqueado com Sucesso!");
                new UsuariosDAO().popularTabela(tblConsulta, tfdConsultar.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Problema ao Bloquear o Usuário!");
            }
            varID = 0;
        }
    }//GEN-LAST:event_btnBloquearActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (tfdNome.getText().length() > 0
                && tfdEmail.getText().length() > 0
                && tfpSenha.getPassword().length > 0
                && tfpConfirmaSenha.getPassword().length > 0) {

            Usuarios usuarios = new Usuarios();
            usuarios.setSenha(String.valueOf(tfpSenha.getPassword()));
            usuarios.setConfirmaSenha(String.valueOf(tfpConfirmaSenha.getPassword()));

            if (usuarios.getSenha().equals(usuarios.getConfirmaSenha())) {
                boolean ativo = cbxSituacao.isSelected();
                String s;
                char situacao;
                if (ativo == true) {
                    s = "a";
                    situacao = s.charAt(0);
                } else {
                    s = "i";
                    situacao = s.charAt(0);
                }
                BCrypt bcrypt = new BCrypt();
                String pwdEncrypt = bcrypt.hashPassword(usuarios.getSenha());
                
                usuarios.setId(varID);
                usuarios.setNome(tfdNome.getText());
                usuarios.setEmail(tfdEmail.getText());
                usuarios.setSenha(pwdEncrypt);
                usuarios.setSituacao(situacao);

                UsuariosDAO usuariosDAO = new UsuariosDAO();

                if (varID == 0) {
                    if (usuariosDAO.salvar(usuarios) == null) {
                        tfdNome.setText("");
                        tfdEmail.setText("");
                        tfpSenha.setText("");
                        tfpConfirmaSenha.setText("");

                        JOptionPane.showMessageDialog(this, "Usuário salvo com sucesso!");
                        tfdNome.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas ao salvar Usuário!");
                    }
                } else {
                    if (usuariosDAO.atualizar(usuarios) == null) {
                        tfdNome.setText("");
                        tfdEmail.setText("");
                        tfpSenha.setText("");
                        tfpConfirmaSenha.setText("");

                        JOptionPane.showMessageDialog(this, "Usuário alterado com sucesso!");
                        tfdNome.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas ao alterar Usuário!");
                    }
                }
                varID = 0;

            } else {
                JOptionPane.showMessageDialog(this, "'Senha' e 'Confirma Senha' são diferentes!");
                tfpSenha.setText("");
                tfpConfirmaSenha.setText("");
                tfpSenha.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher todos os campos!");
            tfdNome.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int row = tblConsulta.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Usuário na Tabela Consulta!");
        } else {
            String idTabela = String.valueOf(tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0));
            varID = Integer.parseInt(idTabela);
            Usuarios usuarios = new UsuariosDAO().consultarId(varID);

            if (usuarios != null) {
                jTabbedPane1.setSelectedIndex(0);
                tfdNome.setText(usuarios.getNome());
                tfdEmail.setText(usuarios.getEmail());
                tfpSenha.setText("");
                tfpConfirmaSenha.setText("");

                tfdNome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Código do Usuário não encontrado!");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        new UsuariosDAO().popularTabela(tblConsulta, tfdConsultar.getText());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        int row = tblConsulta.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Usuário na Tabela Consulta!");
        } else {
            String idTabela = String.valueOf(tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0));
            varID = Integer.parseInt(idTabela);
            if (new UsuariosDAO().desbloquear(varID) == null) {
                JOptionPane.showMessageDialog(this, "Usuário Desbloqueado com Sucesso!");
                new UsuariosDAO().popularTabela(tblConsulta, tfdConsultar.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Problema ao Desbloquear o Usuário!");
            }
            varID = 0;
        }
    }//GEN-LAST:event_btnDesbloquearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloquear;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JScrollPane scrollConsultar;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextField tfdConsultar;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JPasswordField tfpConfirmaSenha;
    private javax.swing.JPasswordField tfpSenha;
    // End of variables declaration//GEN-END:variables
}
