
/**
 * @author Flavio
 */
package tela;

public class FrmPrincipal extends javax.swing.JFrame {

    public FrmPrincipal() {
        initComponents();
        setTitle("Vendas de Mercadorias");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        mniClientes = new javax.swing.JMenuItem();
        mniFornecedores = new javax.swing.JMenuItem();
        mniProdutos = new javax.swing.JMenuItem();
        mniEnderecos = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenu();
        mniPedido = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenu();
        mniCompra = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();
        mniSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        mnuCadastros.setText("Cadastros");

        mniClientes.setText("Clientes");
        mniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniClientes);

        mniFornecedores.setText("Fornecedores");
        mniFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniFornecedores);

        mniProdutos.setText("Produtos");
        mniProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProdutosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniProdutos);

        mniEnderecos.setText("Endereços");
        mniEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEnderecosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniEnderecos);

        jMenuBar1.add(mnuCadastros);

        mnuVendas.setText("Vendas");

        mniPedido.setText("Pedido");
        mniPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPedidoActionPerformed(evt);
            }
        });
        mnuVendas.add(mniPedido);

        jMenuBar1.add(mnuVendas);

        mnuCompras.setText("Compras");

        mniCompra.setText("Compra");
        mniCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCompraActionPerformed(evt);
            }
        });
        mnuCompras.add(mniCompra);

        jMenuBar1.add(mnuCompras);

        mnuRelatorios.setText("Relatórios");
        jMenuBar1.add(mnuRelatorios);

        mnuAjuda.setText("Ajuda");

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuAjuda.add(mniSair);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesActionPerformed
        IfrClientes ifrClientes = new IfrClientes();
        jDesktopPane1.add(ifrClientes);
        ifrClientes.setVisible(true);
    }//GEN-LAST:event_mniClientesActionPerformed

    private void mniFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniFornecedoresActionPerformed

    private void mniProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniProdutosActionPerformed

    private void mniEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEnderecosActionPerformed
        IfrEnderecos ifrEnderecos = new IfrEnderecos();
        jDesktopPane1.add(ifrEnderecos);
        ifrEnderecos.setVisible(true);
    }//GEN-LAST:event_mniEnderecosActionPerformed

    private void mniPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniPedidoActionPerformed

    private void mniCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniCompraActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniClientes;
    private javax.swing.JMenuItem mniCompra;
    private javax.swing.JMenuItem mniEnderecos;
    private javax.swing.JMenuItem mniFornecedores;
    private javax.swing.JMenuItem mniPedido;
    private javax.swing.JMenuItem mniProdutos;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuCompras;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuVendas;
    // End of variables declaration//GEN-END:variables
}
