/**
 * @author Flavio
 */
package tela;

import apoio.ConexaoBD;
import dao.ClienteDAO;
import entidade.Cliente;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class IfrClientes extends javax.swing.JInternalFrame {

    int idCliente = 0;

    /**
     * Creates new form IfrClientes
     */
    public IfrClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientesFechar = new javax.swing.JButton();
        tpnClientes = new javax.swing.JTabbedPane();
        pnlClientesCad = new javax.swing.JPanel();
        lblClientesCadNome = new javax.swing.JLabel();
        tfdClientesCadNome = new javax.swing.JTextField();
        lblClientesCadEmail = new javax.swing.JLabel();
        lblClientesCadCpf = new javax.swing.JLabel();
        lblClientesCadTelefone = new javax.swing.JLabel();
        tfdClientesCadEmail = new javax.swing.JTextField();
        tfdClientesCadCpf = new javax.swing.JTextField();
        tfdClientesCadTelefone = new javax.swing.JTextField();
        pnlClientesCons = new javax.swing.JPanel();
        spnClientesCons = new javax.swing.JScrollPane();
        tblClientesCons = new javax.swing.JTable();
        lblClientesConsConsultar = new javax.swing.JLabel();
        tfdClientesConsConsultar = new javax.swing.JTextField();
        btnClientesConsConsultar = new javax.swing.JButton();
        btnClientesSalvar = new javax.swing.JButton();
        btnClientesEditar = new javax.swing.JButton();
        btnClientesExcluir = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        btnClientesFechar.setText("Fechar");
        btnClientesFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesFecharActionPerformed(evt);
            }
        });

        lblClientesCadNome.setText("Nome: ");

        lblClientesCadEmail.setText("E-mail: ");

        lblClientesCadCpf.setText("CPF: ");

        lblClientesCadTelefone.setText("Telefone: ");

        javax.swing.GroupLayout pnlClientesCadLayout = new javax.swing.GroupLayout(pnlClientesCad);
        pnlClientesCad.setLayout(pnlClientesCadLayout);
        pnlClientesCadLayout.setHorizontalGroup(
            pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientesCadEmail)
                    .addComponent(lblClientesCadCpf)
                    .addComponent(lblClientesCadNome))
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesCadLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tfdClientesCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblClientesCadTelefone)
                        .addGap(26, 26, 26)
                        .addComponent(tfdClientesCadTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                    .addGroup(pnlClientesCadLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdClientesCadNome)
                            .addComponent(tfdClientesCadEmail))))
                .addContainerGap())
        );
        pnlClientesCadLayout.setVerticalGroup(
            pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesCadLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesCadNome)
                    .addComponent(tfdClientesCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesCadEmail)
                    .addComponent(tfdClientesCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesCadCpf)
                    .addComponent(tfdClientesCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClientesCadTelefone)
                    .addComponent(tfdClientesCadTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tpnClientes.addTab("Cadastro", pnlClientesCad);

        tblClientesCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "E-mail", "CPF", "Telefone"
            }
        ));
        spnClientesCons.setViewportView(tblClientesCons);

        lblClientesConsConsultar.setText("Busca");

        btnClientesConsConsultar.setText("Consultar");
        btnClientesConsConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesConsConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesConsLayout = new javax.swing.GroupLayout(pnlClientesCons);
        pnlClientesCons.setLayout(pnlClientesConsLayout);
        pnlClientesConsLayout.setHorizontalGroup(
            pnlClientesConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnClientesCons, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
            .addGroup(pnlClientesConsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientesConsConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdClientesConsConsultar)
                .addGap(18, 18, 18)
                .addComponent(btnClientesConsConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlClientesConsLayout.setVerticalGroup(
            pnlClientesConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesConsLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pnlClientesConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesConsConsultar)
                    .addComponent(tfdClientesConsConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientesConsConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnClientesCons, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tpnClientes.addTab("Consulta", pnlClientesCons);

        btnClientesSalvar.setText("Salvar");
        btnClientesSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesSalvarActionPerformed(evt);
            }
        });

        btnClientesEditar.setText("Editar");
        btnClientesEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesEditarActionPerformed(evt);
            }
        });

        btnClientesExcluir.setText("Excluir");
        btnClientesExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpnClientes)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClientesEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientesSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientesExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientesFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(tpnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesFechar)
                    .addComponent(btnClientesSalvar)
                    .addComponent(btnClientesEditar)
                    .addComponent(btnClientesExcluir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnClientesFecharActionPerformed

    private void btnClientesSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesSalvarActionPerformed
        String nomeCliente = tfdClientesCadNome.getText();
        String nomeEmail = tfdClientesCadEmail.getText();
        String nomeCpf = tfdClientesCadCpf.getText();
        String nomeTelefone = tfdClientesCadTelefone.getText();

        Cliente cliente = new Cliente();
        cliente.setId(idCliente);
        cliente.setNome(nomeCliente);
        cliente.setE_mail(nomeEmail);
        cliente.setCpf(nomeCpf);
        cliente.setTelefone(nomeTelefone);

        ClienteDAO clienteDAO = new ClienteDAO();

        if (idCliente == 0) {
            if (clienteDAO.salvar(cliente) == null) {
                tfdClientesCadNome.setText("");
                tfdClientesCadEmail.setText("");
                tfdClientesCadCpf.setText("");
                tfdClientesCadTelefone.setText("");

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                tfdClientesCadNome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        } else {
            if (clienteDAO.atualizar(cliente) == null) {
                tfdClientesCadNome.setText("");
                tfdClientesCadEmail.setText("");
                tfdClientesCadCpf.setText("");
                tfdClientesCadTelefone.setText("");

                JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
                tfdClientesCadNome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao alterar registro!");
            }
        }
        idCliente = 0;
    }//GEN-LAST:event_btnClientesSalvarActionPerformed

    private void btnClientesEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesEditarActionPerformed
        String idTabela = String.valueOf(tblClientesCons.getValueAt(tblClientesCons.getSelectedRow(), 0));
        idCliente = Integer.parseInt(idTabela);
        Cliente cliente = new ClienteDAO().consultarId(idCliente);

        if (cliente != null) {
            tpnClientes.setSelectedIndex(0);
            tfdClientesCadNome.setText(cliente.getNome());
            tfdClientesCadEmail.setText(cliente.getE_mail());
            tfdClientesCadCpf.setText(cliente.getCpf());
            tfdClientesCadTelefone.setText(cliente.getTelefone());
            tfdClientesCadNome.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Código do cliente não encontrado!");
        }

        tfdClientesCadNome.requestFocus();
    }//GEN-LAST:event_btnClientesEditarActionPerformed

    private void btnClientesConsConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesConsConsultarActionPerformed
        new ClienteDAO().popularTabela(tblClientesCons, tfdClientesConsConsultar.getText());
    }//GEN-LAST:event_btnClientesConsConsultarActionPerformed

    private void btnClientesExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesExcluirActionPerformed
        String idTabela = String.valueOf(tblClientesCons.getValueAt(tblClientesCons.getSelectedRow(), 0));
        idCliente = Integer.parseInt(idTabela);
        if (new ClienteDAO().excluir(idCliente) == null){
            JOptionPane.showMessageDialog(this, "Registro Excluído com Sucesso!");
            new ClienteDAO().popularTabela(tblClientesCons, tfdClientesConsConsultar.getText());
        } else{
            JOptionPane.showMessageDialog(this, "Problema ao excluir o Registro!");
        }
        idCliente = 0;
    }//GEN-LAST:event_btnClientesExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesConsConsultar;
    private javax.swing.JButton btnClientesEditar;
    private javax.swing.JButton btnClientesExcluir;
    private javax.swing.JButton btnClientesFechar;
    private javax.swing.JButton btnClientesSalvar;
    private javax.swing.JLabel lblClientesCadCpf;
    private javax.swing.JLabel lblClientesCadEmail;
    private javax.swing.JLabel lblClientesCadNome;
    private javax.swing.JLabel lblClientesCadTelefone;
    private javax.swing.JLabel lblClientesConsConsultar;
    private javax.swing.JPanel pnlClientesCad;
    private javax.swing.JPanel pnlClientesCons;
    private javax.swing.JScrollPane spnClientesCons;
    private javax.swing.JTable tblClientesCons;
    private javax.swing.JTextField tfdClientesCadCpf;
    private javax.swing.JTextField tfdClientesCadEmail;
    private javax.swing.JTextField tfdClientesCadNome;
    private javax.swing.JTextField tfdClientesCadTelefone;
    private javax.swing.JTextField tfdClientesConsConsultar;
    private javax.swing.JTabbedPane tpnClientes;
    // End of variables declaration//GEN-END:variables
}
