/**
 * @author Flavio
 */
package tela;

import apoio.Formatacao;
import dao.EnderecosDAO;
import entidade.Enderecos;
import javax.swing.JOptionPane;

public class IfrEnderecos extends javax.swing.JInternalFrame {

    int idEndereco = 0;
    
    public IfrEnderecos() {
        initComponents();
        
        Formatacao.formatarCep(tffEnderecosCadCep);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnEnderecos = new javax.swing.JTabbedPane();
        pnlEnderecosCad = new javax.swing.JPanel();
        lblEnderecosCadEnd = new javax.swing.JLabel();
        lblEnderecosCadCep = new javax.swing.JLabel();
        tfdEnderecosCadEnd = new javax.swing.JTextField();
        tffEnderecosCadCep = new javax.swing.JFormattedTextField();
        pnlEnderecosCons = new javax.swing.JPanel();
        lblEnderecosConsBusca = new javax.swing.JLabel();
        tfdEnderecosConsConsultar = new javax.swing.JTextField();
        btnEnderecosConsConsultar = new javax.swing.JButton();
        spnEnderecosCons = new javax.swing.JScrollPane();
        tblEnderecosCons = new javax.swing.JTable();
        btnEnderecosFechar = new javax.swing.JButton();
        btnEnderecosExcluir = new javax.swing.JButton();
        btnEnderecosSalvar = new javax.swing.JButton();
        btnEnderecosEditar = new javax.swing.JButton();

        setTitle("Cadastro de Endereços");

        lblEnderecosCadEnd.setText("Endereço:");

        lblEnderecosCadCep.setText("CEP:");

        javax.swing.GroupLayout pnlEnderecosCadLayout = new javax.swing.GroupLayout(pnlEnderecosCad);
        pnlEnderecosCad.setLayout(pnlEnderecosCadLayout);
        pnlEnderecosCadLayout.setHorizontalGroup(
            pnlEnderecosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecosCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnderecosCadEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnderecosCadCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnderecosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdEnderecosCadEnd)
                    .addGroup(pnlEnderecosCadLayout.createSequentialGroup()
                        .addComponent(tffEnderecosCadCep, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 477, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEnderecosCadLayout.setVerticalGroup(
            pnlEnderecosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecosCadLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlEnderecosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecosCadEnd)
                    .addComponent(tfdEnderecosCadEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEnderecosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecosCadCep)
                    .addComponent(tffEnderecosCadCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tpnEnderecos.addTab("Cadastro", pnlEnderecosCad);

        lblEnderecosConsBusca.setText("Busca");

        btnEnderecosConsConsultar.setText("Consultar");
        btnEnderecosConsConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecosConsConsultarActionPerformed(evt);
            }
        });

        tblEnderecosCons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Endereço", "CEP"
            }
        ));
        spnEnderecosCons.setViewportView(tblEnderecosCons);

        javax.swing.GroupLayout pnlEnderecosConsLayout = new javax.swing.GroupLayout(pnlEnderecosCons);
        pnlEnderecosCons.setLayout(pnlEnderecosConsLayout);
        pnlEnderecosConsLayout.setHorizontalGroup(
            pnlEnderecosConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnderecosConsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecosConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spnEnderecosCons, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(pnlEnderecosConsLayout.createSequentialGroup()
                        .addComponent(lblEnderecosConsBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdEnderecosConsConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnderecosConsConsultar)))
                .addContainerGap())
        );
        pnlEnderecosConsLayout.setVerticalGroup(
            pnlEnderecosConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecosConsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecosConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecosConsBusca)
                    .addComponent(tfdEnderecosConsConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnderecosConsConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnEnderecosCons, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpnEnderecos.addTab("Consulta", pnlEnderecosCons);

        btnEnderecosFechar.setText("Fechar");
        btnEnderecosFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecosFecharActionPerformed(evt);
            }
        });

        btnEnderecosExcluir.setText("Excluir");
        btnEnderecosExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecosExcluirActionPerformed(evt);
            }
        });

        btnEnderecosSalvar.setText("Salvar");
        btnEnderecosSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecosSalvarActionPerformed(evt);
            }
        });

        btnEnderecosEditar.setText("Editar");
        btnEnderecosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecosEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnEnderecos)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnderecosEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEnderecosSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnEnderecosExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnEnderecosFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpnEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnderecosFechar)
                    .addComponent(btnEnderecosExcluir)
                    .addComponent(btnEnderecosSalvar)
                    .addComponent(btnEnderecosEditar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnderecosFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecosFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEnderecosFecharActionPerformed

    private void btnEnderecosExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecosExcluirActionPerformed
        String idTabela = String.valueOf(tblEnderecosCons.getValueAt(tblEnderecosCons.getSelectedRow(), 0));
        idEndereco = Integer.parseInt(idTabela);
        if (new EnderecosDAO().excluir(idEndereco) == null){
            JOptionPane.showMessageDialog(this, "Registro Excluído com Sucesso!");
            new EnderecosDAO().popularTabela(tblEnderecosCons, tfdEnderecosConsConsultar.getText());
        } else{
            JOptionPane.showMessageDialog(this, "Problema ao excluir o Registro!");
        }
        idEndereco = 0;
    }//GEN-LAST:event_btnEnderecosExcluirActionPerformed

    private void btnEnderecosSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecosSalvarActionPerformed
        String nomeEndereco = tfdEnderecosCadEnd.getText();
        String nomeCep = tffEnderecosCadCep.getText();

        Enderecos endereco = new Enderecos();
        endereco.setId(idEndereco);
        endereco.setDescricao(nomeEndereco);
        endereco.setCep(nomeCep);

        EnderecosDAO enderecoDAO = new EnderecosDAO();

        if (idEndereco == 0) {
            if (enderecoDAO.salvar(endereco) == null) {
                tfdEnderecosCadEnd.setText("");
                tffEnderecosCadCep.setText("");

                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                tfdEnderecosCadEnd.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        } else {
            if (enderecoDAO.atualizar(endereco) == null) {
                tfdEnderecosCadEnd.setText("");
                tffEnderecosCadCep.setText("");

                JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!");
                tfdEnderecosCadEnd.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao alterar registro!");
            }
        }
        idEndereco = 0;
    }//GEN-LAST:event_btnEnderecosSalvarActionPerformed

    private void btnEnderecosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecosEditarActionPerformed
        String idTabela = String.valueOf(tblEnderecosCons.getValueAt(tblEnderecosCons.getSelectedRow(), 0));
        idEndereco = Integer.parseInt(idTabela);
        Enderecos endereco = new EnderecosDAO().consultarId(idEndereco);

        if (endereco != null) {
            tpnEnderecos.setSelectedIndex(0);
            tfdEnderecosCadEnd.setText(endereco.getDescricao());
            tffEnderecosCadCep.setText(endereco.getCep());
            
            tfdEnderecosCadEnd.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Código do endereço não encontrado!");
        }
    }//GEN-LAST:event_btnEnderecosEditarActionPerformed

    private void btnEnderecosConsConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecosConsConsultarActionPerformed
        new EnderecosDAO().popularTabela(tblEnderecosCons, tfdEnderecosConsConsultar.getText());
    }//GEN-LAST:event_btnEnderecosConsConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnderecosConsConsultar;
    private javax.swing.JButton btnEnderecosEditar;
    private javax.swing.JButton btnEnderecosExcluir;
    private javax.swing.JButton btnEnderecosFechar;
    private javax.swing.JButton btnEnderecosSalvar;
    private javax.swing.JLabel lblEnderecosCadCep;
    private javax.swing.JLabel lblEnderecosCadEnd;
    private javax.swing.JLabel lblEnderecosConsBusca;
    private javax.swing.JPanel pnlEnderecosCad;
    private javax.swing.JPanel pnlEnderecosCons;
    private javax.swing.JScrollPane spnEnderecosCons;
    private javax.swing.JTable tblEnderecosCons;
    private javax.swing.JTextField tfdEnderecosCadEnd;
    private javax.swing.JTextField tfdEnderecosConsConsultar;
    private javax.swing.JFormattedTextField tffEnderecosCadCep;
    private javax.swing.JTabbedPane tpnEnderecos;
    // End of variables declaration//GEN-END:variables
}
