/**
 * @author Flavio
 */

package tela;

import apoio.ConexaoBD;
import dao.ClienteDAO;
import entidade.Cliente;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class IfrClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrClientes
     */
    public IfrClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientesFechar = new javax.swing.JButton();
        tpnClientes = new javax.swing.JTabbedPane();
        pnlClientesCad = new javax.swing.JPanel();
        lblClientesCadNome = new javax.swing.JLabel();
        tfdClientesCadNome = new javax.swing.JTextField();
        lblClientesCadEmail = new javax.swing.JLabel();
        lblClientesCadCpf = new javax.swing.JLabel();
        lblClientesCadTelefone = new javax.swing.JLabel();
        tfdClientesCadEmail = new javax.swing.JTextField();
        tfdClientesCadCpf = new javax.swing.JTextField();
        tfdClientesCadTelefone = new javax.swing.JTextField();
        btnClientesCadSalvar = new javax.swing.JButton();
        btnClientesCadCancelar = new javax.swing.JButton();
        pnlClientesConsulta = new javax.swing.JPanel();
        spn1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        btnClientesCadConsultar = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        btnClientesFechar.setText("Fechar");
        btnClientesFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesFecharActionPerformed(evt);
            }
        });

        lblClientesCadNome.setText("Nome: ");

        lblClientesCadEmail.setText("E-mail: ");

        lblClientesCadCpf.setText("CPF: ");

        lblClientesCadTelefone.setText("Telefone: ");

        btnClientesCadSalvar.setText("Salvar");
        btnClientesCadSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesCadSalvarActionPerformed(evt);
            }
        });

        btnClientesCadCancelar.setText("Cancelar");
        btnClientesCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesCadCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesCadLayout = new javax.swing.GroupLayout(pnlClientesCad);
        pnlClientesCad.setLayout(pnlClientesCadLayout);
        pnlClientesCadLayout.setHorizontalGroup(
            pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesCadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientesCadEmail)
                    .addComponent(lblClientesCadCpf)
                    .addComponent(lblClientesCadNome))
                .addGap(29, 29, 29)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdClientesCadNome)
                    .addComponent(tfdClientesCadEmail)
                    .addGroup(pnlClientesCadLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfdClientesCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblClientesCadTelefone)
                        .addGap(26, 26, 26)
                        .addComponent(tfdClientesCadTelefone))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesCadLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(btnClientesCadCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientesCadSalvar)
                        .addGap(244, 244, 244)))
                .addContainerGap())
        );
        pnlClientesCadLayout.setVerticalGroup(
            pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesCadLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesCadNome)
                    .addComponent(tfdClientesCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesCadEmail)
                    .addComponent(tfdClientesCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientesCadCpf)
                    .addComponent(tfdClientesCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClientesCadTelefone)
                    .addComponent(tfdClientesCadTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlClientesCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesCadSalvar)
                    .addComponent(btnClientesCadCancelar))
                .addGap(15, 15, 15))
        );

        tpnClientes.addTab("Cadastro", pnlClientesCad);

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "E-mail", "CPF", "Telefone"
            }
        ));
        spn1.setViewportView(tbl1);

        btnClientesCadConsultar.setText("Consultar");
        btnClientesCadConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesCadConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesConsultaLayout = new javax.swing.GroupLayout(pnlClientesConsulta);
        pnlClientesConsulta.setLayout(pnlClientesConsultaLayout);
        pnlClientesConsultaLayout.setHorizontalGroup(
            pnlClientesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spn1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(pnlClientesConsultaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClientesCadConsultar))
        );
        pnlClientesConsultaLayout.setVerticalGroup(
            pnlClientesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesConsultaLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btnClientesCadConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spn1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpnClientes.addTab("Consulta", pnlClientesConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClientesFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(tpnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientesFechar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnClientesFecharActionPerformed

    private void btnClientesCadSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesCadSalvarActionPerformed
        String nomeCliente = tfdClientesCadNome.getText();
        String nomeEmail = tfdClientesCadEmail.getText();
        String nomeCpf = tfdClientesCadCpf.getText();
        String nomeTelefone = tfdClientesCadTelefone.getText();
        
        Cliente cliente = new Cliente();
        cliente.setNome(nomeCliente);
        cliente.setE_mail(nomeEmail);
        cliente.setCpf(nomeCpf);
        cliente.setTelefone(nomeTelefone);

        ClienteDAO clienteDAO = new ClienteDAO();

        if (clienteDAO.salvar(cliente) == null) {
            tfdClientesCadNome.setText("");
            tfdClientesCadEmail.setText("");
            tfdClientesCadCpf.setText("");
            tfdClientesCadTelefone.setText("");

            JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");

            tfdClientesCadNome.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
        }
    }//GEN-LAST:event_btnClientesCadSalvarActionPerformed

    private void btnClientesCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesCadCancelarActionPerformed
        tfdClientesCadNome.setText("");
        tfdClientesCadEmail.setText("");
        tfdClientesCadCpf.setText("");
        tfdClientesCadTelefone.setText("");
        
        JOptionPane.showMessageDialog(this, "Registro cancelado!");
        tfdClientesCadNome.requestFocus();
    }//GEN-LAST:event_btnClientesCadCancelarActionPerformed

    private void btnClientesCadConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesCadConsultarActionPerformed
        ArrayList<Cliente> clientes = new ArrayList();

        clientes = new ClienteDAO().consultarTodos();

        for (int i=0; i<clientes.size(); i++) {
            System.out.println("ID: " + clientes.get(i).getId());
            System.out.println("Nome: " + clientes.get(i).getNome());
            System.out.println("E-mail: " + clientes.get(i).getE_mail());
            System.out.println("CPF: " + clientes.get(i).getCpf());
            System.out.println("Telefone: " + clientes.get(i).getTelefone());
            
            System.out.println("");
        }
    }//GEN-LAST:event_btnClientesCadConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesCadCancelar;
    private javax.swing.JButton btnClientesCadConsultar;
    private javax.swing.JButton btnClientesCadSalvar;
    private javax.swing.JButton btnClientesFechar;
    private javax.swing.JLabel lblClientesCadCpf;
    private javax.swing.JLabel lblClientesCadEmail;
    private javax.swing.JLabel lblClientesCadNome;
    private javax.swing.JLabel lblClientesCadTelefone;
    private javax.swing.JPanel pnlClientesCad;
    private javax.swing.JPanel pnlClientesConsulta;
    private javax.swing.JScrollPane spn1;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField tfdClientesCadCpf;
    private javax.swing.JTextField tfdClientesCadEmail;
    private javax.swing.JTextField tfdClientesCadNome;
    private javax.swing.JTextField tfdClientesCadTelefone;
    private javax.swing.JTabbedPane tpnClientes;
    // End of variables declaration//GEN-END:variables
}
